modLoader = "javafml"

loaderVersion = "[35,)"

license = "GPL v3"

issueTrackerURL = "https://github.com/blueminecraftteam/HealthMod/issues/"

[[mods]]

modId = "healthmod"

version = "${version}"

displayName = "HealthMod"

description = "This mod adds health related items into Minecraft, such as viruses, medicines and more!"

logoFile = "logo.png"

credits = "xf8b, AG6, LoneWolf, ilja615, Saksham4106, PTZ"

authors = "Blue Minecraft Team"

[[dependencies.healthmod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4]"
ordering = "NONE"
side = "BOTH"
